import { initializeApp, getApps, getApp } from 'https://www.gstatic.com/firebasejs/10.11.0/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.11.0/firebase-auth.js';

const ADMIN_EMAIL='admin@centralfreefire.com.br';
const W=3000,H=3749,FONT='Avilock';
const DB='cff-admin-photo-editor-v1',STORE='assets',FRAME_KEY='custom-frame';
const config=window.CFF_CONFIG?.firebase;
if(!config){location.replace('admin.html');throw new Error('Configuração do Firebase não encontrada.');}
const app=getApps().length?getApp():initializeApp(config),auth=getAuth(app),$=s=>document.querySelector(s);
const ui={
 app:$('#photo-editor-app'),authMessage:$('#photo-editor-auth-message'),file:$('#photo-editor-file'),imageName:$('#photo-editor-image-name'),canvas:$('#photo-editor-canvas'),stage:$('#photo-editor-stage'),empty:$('#photo-editor-empty'),status:$('#photo-editor-canvas-status'),
 resetAll:$('#photo-editor-reset-all'),fitCover:$('#photo-editor-fit-cover'),fitContain:$('#photo-editor-fit-contain'),center:$('#photo-editor-center'),flip:$('#photo-editor-flip'),zoom:$('#photo-editor-zoom'),zoomValue:$('#photo-editor-zoom-value'),rotation:$('#photo-editor-rotation'),rotationValue:$('#photo-editor-rotation-value'),
 brightness:$('#photo-editor-brightness'),brightnessValue:$('#photo-editor-brightness-value'),contrast:$('#photo-editor-contrast'),contrastValue:$('#photo-editor-contrast-value'),saturation:$('#photo-editor-saturation'),saturationValue:$('#photo-editor-saturation-value'),resetAdjustments:$('#photo-editor-reset-adjustments'),
 text:$('#photo-editor-text'),fontSize:$('#photo-editor-font-size'),textColor:$('#photo-editor-text-color'),textX:$('#photo-editor-text-x'),textXValue:$('#photo-editor-text-x-value'),textY:$('#photo-editor-text-y'),textYValue:$('#photo-editor-text-y-value'),textSpacing:$('#photo-editor-text-spacing'),textSpacingValue:$('#photo-editor-text-spacing-value'),textShadow:$('#photo-editor-text-shadow'),fontFile:$('#photo-editor-font-file'),fontStatus:$('#photo-editor-font-status'),
 frameEnabled:$('#photo-editor-frame-enabled'),frameFile:$('#photo-editor-frame-file'),frameStatus:$('#photo-editor-frame-status'),clearFrame:$('#photo-editor-clear-frame'),size:$('#photo-editor-size'),format:$('#photo-editor-format'),qualityWrap:$('#photo-editor-quality-wrap'),quality:$('#photo-editor-quality'),qualityValue:$('#photo-editor-quality-value'),fileName:$('#photo-editor-file-name'),download:$('#photo-editor-download'),message:$('#photo-editor-message')
};
const ctx=ui.canvas.getContext('2d',{alpha:false,desynchronized:true});
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const s={image:null,imageUrl:'',baseScale:1,zoom:1,x:W/2,y:H/2,rotation:0,flipX:1,brightness:100,contrast:100,saturation:100,text:'',textSize:160,textColor:'#ffffff',textX:50,textY:82,textSpacing:92,textShadow:true,frameEnabled:true,frame:null,frameUrl:'',logo:null,fontReady:false,pointers:new Map(),dragId:null,pinch:null,renderQueued:false};
let initialized=false;

function msg(t,type=''){ui.message.textContent=t||'';ui.message.classList.toggle('is-error',type==='error');ui.message.classList.toggle('is-success',type==='success');}
function queue(){if(s.renderQueued)return;s.renderQueued=true;requestAnimationFrame(()=>{s.renderQueued=false;render();});}
function rounded(c,x,y,w,h,r){r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath();}
function background(c){const g=c.createLinearGradient(0,0,W,H);g.addColorStop(0,'#0b0d14');g.addColorStop(.56,'#12161d');g.addColorStop(1,'#020304');c.fillStyle=g;c.fillRect(0,0,W,H);c.save();c.globalAlpha=.16;const r=c.createRadialGradient(W*.5,H*.34,40,W*.5,H*.34,W*.48);r.addColorStop(0,'#f3c66a');r.addColorStop(.18,'rgba(243,198,106,.65)');r.addColorStop(.45,'rgba(243,198,106,.12)');r.addColorStop(1,'rgba(243,198,106,0)');c.fillStyle=r;c.fillRect(0,0,W,H);c.restore();}
function photo(c){if(!s.image)return;const sc=s.baseScale*s.zoom,w=s.image.naturalWidth*sc,h=s.image.naturalHeight*sc;c.save();c.filter=`brightness(${s.brightness}%) contrast(${s.contrast}%) saturate(${s.saturation}%)`;c.translate(s.x,s.y);c.rotate(s.rotation*Math.PI/180);c.scale(s.flipX,1);c.drawImage(s.image,-w/2,-h/2,w,h);c.restore();c.filter='none';}
function wrap(c,text,max){const out=[];String(text||'').split(/\n/).forEach(p=>{const words=p.trim().split(/\s+/).filter(Boolean);if(!words.length){out.push('');return;}let line=words.shift();for(const word of words){const test=`${line} ${word}`;if(c.measureText(test).width<=max)line=test;else{out.push(line);line=word;}}out.push(line);});return out.slice(0,6);}
function textLayer(c){const text=String(s.text||'').trim();if(!text)return;const size=clamp(+s.textSize||160,40,500),x=W*(clamp(+s.textX||50,5,95)/100),y=H*(clamp(+s.textY||82,8,92)/100),lineH=size*(clamp(+s.textSpacing||92,70,180)/100);c.save();c.textAlign='center';c.textBaseline='middle';c.font=`${size}px ${s.fontReady?'"Avilock"':'Impact, "Arial Black", sans-serif'}`;c.fillStyle=s.textColor||'#fff';if(s.textShadow){c.shadowColor='rgba(0,0,0,.62)';c.shadowBlur=Math.max(10,size*.08);c.shadowOffsetY=Math.max(4,size*.035);}const lines=wrap(c,text.toUpperCase(),W*.84),start=y-((lines.length-1)*lineH)/2;lines.forEach((line,i)=>c.fillText(line,x,start+i*lineH));c.restore();}
function brand(c){const x=W*.73,y=H*.89,ls=230;if(s.logo?.complete&&s.logo.naturalWidth){const r=s.logo.naturalWidth/s.logo.naturalHeight,lw=r>=1?ls:ls*r,lh=r>=1?ls/r:ls;c.drawImage(s.logo,x-lw-40,y-lh/2,lw,lh);}c.textAlign='left';c.textBaseline='alphabetic';c.fillStyle='#fff';c.shadowColor='rgba(0,0,0,.45)';c.shadowBlur=8;c.shadowOffsetY=3;const f=s.fontReady?'"Avilock"':'Impact, "Arial Black", sans-serif';c.font=`150px ${f}`;c.fillText('CENTRAL',x,y-18);c.font=`92px ${f}`;c.fillText('FREE FIRE',x,y+88);c.shadowColor='transparent';}
function defaultFrame(c){c.save();c.fillStyle='#fff';c.beginPath();c.moveTo(0,H*.655);c.bezierCurveTo(W*.08,H*.69,W*.24,H*.78,W*.39,H*.79);c.bezierCurveTo(W*.56,H*.80,W*.66,H*.75,W*.79,H*.78);c.bezierCurveTo(W*.88,H*.80,W*.94,H*.83,W,H*.85);c.lineTo(W,H);c.lineTo(0,H);c.closePath();c.fill();rounded(c,72,72,W-144,H-144,390);c.lineWidth=86;c.strokeStyle='#070707';c.stroke();c.lineWidth=56;c.strokeStyle='#fff';c.stroke();c.lineWidth=15;c.strokeStyle='#070707';c.stroke();c.fillStyle='#050505';c.beginPath();c.moveTo(W*.955,H*.84);c.lineTo(W*.955,H*.93);c.lineTo(W*.995,H*.915);c.lineTo(W*.995,H*.825);c.closePath();c.fill();brand(c);c.restore();}
function frame(c){if(!s.frameEnabled)return;if(s.frame)c.drawImage(s.frame,0,0,W,H);else defaultFrame(c);}
function render(){ctx.clearRect(0,0,W,H);background(ctx);photo(ctx);frame(ctx);textLayer(ctx);ui.empty.hidden=!!s.image;ui.download.disabled=!s.image;ui.status.textContent=s.image?`${s.image.naturalWidth} × ${s.image.naturalHeight} • arraste para mover • pinça para zoom`:'Adicione uma foto para começar';}
function fit(mode='cover'){if(!s.image)return;const sx=W/s.image.naturalWidth,sy=H/s.image.naturalHeight;s.baseScale=mode==='contain'?Math.min(sx,sy):Math.max(sx,sy);s.zoom=1;s.x=W/2;s.y=H/2;ui.zoom.value='100';ui.zoomValue.textContent='100%';queue();}
function loadPhoto(file){if(!file||!/^image\/(png|jpeg|webp)$/i.test(file.type)){msg('Escolha uma imagem PNG, JPG ou WEBP.','error');return;}if(s.imageUrl)URL.revokeObjectURL(s.imageUrl);const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{s.image=img;s.imageUrl=url;ui.imageName.textContent=file.name;s.rotation=0;s.flipX=1;ui.rotation.value='0';ui.rotationValue.textContent='0°';fit('cover');msg('Foto carregada. Ajuste no preview e exporte quando estiver pronta.','success');};img.onerror=()=>{URL.revokeObjectURL(url);msg('Não foi possível abrir essa imagem.','error');};img.src=url;}
function resetAdjust(){s.brightness=s.contrast=s.saturation=100;for(const [el,out] of [[ui.brightness,ui.brightnessValue],[ui.contrast,ui.contrastValue],[ui.saturation,ui.saturationValue]]){el.value='100';out.textContent='100%';}queue();}
function resetAll(){s.rotation=0;s.flipX=1;s.text='';s.textSize=160;s.textColor='#ffffff';s.textX=50;s.textY=82;s.textSpacing=92;s.textShadow=true;ui.rotation.value='0';ui.rotationValue.textContent='0°';ui.text.value='';ui.fontSize.value='160';ui.textColor.value='#ffffff';ui.textX.value='50';ui.textXValue.textContent='50%';ui.textY.value='82';ui.textYValue.textContent='82%';ui.textSpacing.value='92';ui.textSpacingValue.textContent='92%';ui.textShadow.checked=true;resetAdjust();if(s.image)fit('cover');else queue();msg('Ajustes resetados.','success');}
function point(e){const r=ui.stage.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H};}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function mid(a,b){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}
function syncZoom(){const p=Math.round(s.zoom*100);ui.zoom.value=String(p);ui.zoomValue.textContent=`${p}%`;}
function beginPinch(){const pts=[...s.pointers.values()];if(pts.length<2)return;const [a,b]=pts,m=mid(a,b);s.dragId=null;s.pinch={distance:Math.max(dist(a,b),1),zoom:s.zoom,cx:m.x,cy:m.y,x:s.x,y:s.y};}
function down(e){if(!s.image)return;e.preventDefault();const p=point(e);s.pointers.set(e.pointerId,p);ui.stage.setPointerCapture?.(e.pointerId);if(s.pointers.size===1){s.dragId=e.pointerId;s.last=p;s.pinch=null;}else beginPinch();}
function move(e){if(!s.pointers.has(e.pointerId))return;e.preventDefault();const p=point(e);s.pointers.set(e.pointerId,p);if(s.pointers.size>=2){if(!s.pinch)beginPinch();const [a,b]=[...s.pointers.values()],m=mid(a,b);s.zoom=clamp(s.pinch.zoom*(Math.max(dist(a,b),1)/s.pinch.distance),.25,3);s.x=s.pinch.x+(m.x-s.pinch.cx);s.y=s.pinch.y+(m.y-s.pinch.cy);syncZoom();queue();return;}if(s.dragId===e.pointerId){s.x+=p.x-s.last.x;s.y+=p.y-s.last.y;s.last=p;queue();}}
function up(e){s.pointers.delete(e.pointerId);ui.stage.releasePointerCapture?.(e.pointerId);if(s.pointers.size>=2){beginPinch();return;}s.pinch=null;if(s.pointers.size===1){const [id,p]=[...s.pointers.entries()][0];s.dragId=id;s.last=p;}else s.dragId=null;}
function filename(v){return String(v||'central-free-fire-edit').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)||'central-free-fire-edit';}
function download(){if(!s.image){msg('Adicione uma foto antes de exportar.','error');return;}render();const [w,h]=ui.size.value.split('x').map(Number),out=document.createElement('canvas');out.width=w;out.height=h;const c=out.getContext('2d',{alpha:false});c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';c.drawImage(ui.canvas,0,0,W,H,0,0,w,h);const jpg=ui.format.value==='jpg',mime=jpg?'image/jpeg':'image/png',q=jpg?clamp(+ui.quality.value/100,.6,1):undefined,name=`${filename(ui.fileName.value)}-${w}x${h}.${jpg?'jpg':'png'}`;ui.download.disabled=true;ui.download.textContent='Gerando...';out.toBlob(blob=>{ui.download.disabled=false;ui.download.textContent='Baixar arte';if(!blob){msg('Não foi possível gerar o arquivo.','error');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);msg(`Arte exportada em ${w} × ${h}.`,'success');},mime,q);}
async function loadFont(file){if(!file)return;try{const face=new FontFace(FONT,await file.arrayBuffer());await face.load();document.fonts.add(face);s.fontReady=true;fontStatus();queue();msg('Fonte Avilock carregada nesta sessão.','success');}catch(e){console.error(e);msg('Não consegui carregar esse arquivo de fonte.','error');}}
function fontStatus(){s.fontReady=document.fonts.check('24px "Avilock"')||s.fontReady;ui.fontStatus.textContent=s.fontReady?'Avilock ativa':'Fallback ativo';ui.fontStatus.classList.toggle('is-ready',s.fontReady);ui.fontStatus.classList.toggle('is-warning',!s.fontReady);}
function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error);});}
async function dbPut(blob){try{const db=await openDb();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(blob,FRAME_KEY);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();}catch(e){console.warn(e)}}
async function dbGet(){try{const db=await openDb(),v=await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readonly'),q=tx.objectStore(STORE).get(FRAME_KEY);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)});db.close();return v;}catch{return null}}
async function dbDelete(){try{const db=await openDb();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(FRAME_KEY);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();}catch{}}
function frameStatus(t){ui.frameStatus.textContent=t;ui.frameStatus.classList.add('is-ready');}
function loadFrame(blob,persist=true){if(!blob)return;if(s.frameUrl)URL.revokeObjectURL(s.frameUrl);const url=URL.createObjectURL(blob),img=new Image();img.onload=async()=>{s.frame=img;s.frameUrl=url;frameStatus('Frente personalizada');if(persist)await dbPut(blob);queue();msg('Imagem da frente aplicada por cima da foto.','success');};img.onerror=()=>{URL.revokeObjectURL(url);msg('Não foi possível abrir essa moldura.','error');};img.src=url;}
async function clearFrame(){if(s.frameUrl)URL.revokeObjectURL(s.frameUrl);s.frame=null;s.frameUrl='';ui.frameFile.value='';await dbDelete();frameStatus('Padrão');queue();msg('Moldura padrão restaurada.','success');}
function bind(){ui.file.addEventListener('change',()=>loadPhoto(ui.file.files?.[0]));ui.resetAll.addEventListener('click',resetAll);ui.fitCover.addEventListener('click',()=>fit('cover'));ui.fitContain.addEventListener('click',()=>fit('contain'));ui.center.addEventListener('click',()=>{s.x=W/2;s.y=H/2;queue()});ui.flip.addEventListener('click',()=>{s.flipX*=-1;queue()});ui.zoom.addEventListener('input',()=>{s.zoom=clamp(+ui.zoom.value/100,.25,3);syncZoom();queue()});ui.rotation.addEventListener('input',()=>{s.rotation=+ui.rotation.value;ui.rotationValue.textContent=`${s.rotation}°`;queue()});
 for(const [el,out,key] of [[ui.brightness,ui.brightnessValue,'brightness'],[ui.contrast,ui.contrastValue,'contrast'],[ui.saturation,ui.saturationValue,'saturation']])el.addEventListener('input',()=>{s[key]=+el.value;out.textContent=`${s[key]}%`;queue()});ui.resetAdjustments.addEventListener('click',resetAdjust);
 ui.text.addEventListener('input',()=>{s.text=ui.text.value;queue()});ui.fontSize.addEventListener('input',()=>{s.textSize=clamp(+ui.fontSize.value||160,40,500);queue()});ui.textColor.addEventListener('input',()=>{s.textColor=ui.textColor.value;queue()});ui.textX.addEventListener('input',()=>{s.textX=+ui.textX.value;ui.textXValue.textContent=`${s.textX}%`;queue()});ui.textY.addEventListener('input',()=>{s.textY=+ui.textY.value;ui.textYValue.textContent=`${s.textY}%`;queue()});ui.textSpacing.addEventListener('input',()=>{s.textSpacing=+ui.textSpacing.value;ui.textSpacingValue.textContent=`${s.textSpacing}%`;queue()});ui.textShadow.addEventListener('change',()=>{s.textShadow=ui.textShadow.checked;queue()});ui.fontFile.addEventListener('change',()=>loadFont(ui.fontFile.files?.[0]));
 ui.frameEnabled.addEventListener('change',()=>{s.frameEnabled=ui.frameEnabled.checked;queue()});ui.frameFile.addEventListener('change',()=>{const f=ui.frameFile.files?.[0];if(!f||!/^image\/(png|webp)$/i.test(f.type)){msg('Escolha uma moldura PNG ou WEBP.','error');return;}loadFrame(f)});ui.clearFrame.addEventListener('click',clearFrame);
 for(const [ev,fn] of [['pointerdown',down],['pointermove',move],['pointerup',up],['pointercancel',up],['pointerleave',up]])ui.stage.addEventListener(ev,fn);ui.stage.addEventListener('wheel',e=>{if(!s.image)return;e.preventDefault();s.zoom=clamp(s.zoom+(e.deltaY<0?.05:-.05),.25,3);syncZoom();queue()},{passive:false});ui.format.addEventListener('change',()=>ui.qualityWrap.hidden=ui.format.value!=='jpg');ui.quality.addEventListener('input',()=>ui.qualityValue.textContent=`${ui.quality.value}%`);ui.download.addEventListener('click',download);}
async function init(){if(initialized)return;initialized=true;bind();const logo=new Image();logo.onload=()=>{s.logo=logo;queue()};logo.src='central free fire.webp';fontStatus();document.fonts.ready.then(()=>{fontStatus();queue()});const saved=await dbGet();if(saved)loadFrame(saved,false);else frameStatus('Padrão');render();}
onAuthStateChanged(auth,async user=>{if(!user||String(user.email||'').toLowerCase()!==ADMIN_EMAIL){location.replace('admin.html');return;}ui.authMessage.hidden=true;ui.app.hidden=false;await init();});
