import { initializeApp, getApps, getApp } from 'https://www.gstatic.com/firebasejs/10.11.0/firebase-app.js';
import { getAuth, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.11.0/firebase-auth.js';

const ADMIN_EMAIL='admin@centralfreefire.com.br';
const W=3000,H=3749,FONT='Avilock';
const PREVIEW_W=1200,PREVIEW_H=Math.round(H*PREVIEW_W/W);
const OFFICIAL_FONT_URL='assets/fonts/avilock-bold.woff2?v=20260913-official-v1';
const DB='cff-admin-photo-editor-v1',STORE='assets',FRAME_KEY='custom-frame',FONT_KEY='avilock-font';
const TEXT_DEFAULTS_KEY='cff-admin-photo-editor-text-defaults-v1';
const ORIGINAL_TEXT_DEFAULTS={font:'Avilock',size:190,color:'#ffffff',x:50,y:86,spacing:106,shadow:true};
const config=window.CFF_CONFIG?.firebase;
if(!config){location.replace('admin.html');throw new Error('Configuração do Firebase não encontrada.');}
const app=getApps().length?getApp():initializeApp(config),auth=getAuth(app),$=s=>document.querySelector(s);
const ui={
  app:$('#photo-editor-app'),authMessage:$('#photo-editor-auth-message'),file:$('#photo-editor-file'),imageName:$('#photo-editor-image-name'),canvas:$('#photo-editor-canvas'),stage:$('#photo-editor-stage'),empty:$('#photo-editor-empty'),status:$('#photo-editor-canvas-status'),
  addPipTop:$('#photo-editor-add-pip-top'),deleteMain:$('#photo-editor-delete-main'),deleteMainDialog:$('#photo-editor-delete-main-dialog'),confirmDeleteMain:$('#photo-editor-confirm-delete-main'),
  resetAll:$('#photo-editor-reset-all'),fitCover:$('#photo-editor-fit-cover'),fitContain:$('#photo-editor-fit-contain'),center:$('#photo-editor-center'),flip:$('#photo-editor-flip'),zoom:$('#photo-editor-zoom'),zoomValue:$('#photo-editor-zoom-value'),pinchLock:$('#photo-editor-pinch-lock'),rotation:$('#photo-editor-rotation'),rotationValue:$('#photo-editor-rotation-value'),
  brightness:$('#photo-editor-brightness'),brightnessValue:$('#photo-editor-brightness-value'),contrast:$('#photo-editor-contrast'),contrastValue:$('#photo-editor-contrast-value'),saturation:$('#photo-editor-saturation'),saturationValue:$('#photo-editor-saturation-value'),resetAdjustments:$('#photo-editor-reset-adjustments'),
  pipFile:$('#photo-editor-pip-file'),pipEnabled:$('#photo-editor-pip-enabled'),pipStatus:$('#photo-editor-pip-status'),pipLayers:$('#photo-editor-pip-layers'),pasteImage:$('#photo-editor-paste-image'),duplicatePip:$('#photo-editor-duplicate-pip'),pipFront:$('#photo-editor-pip-front'),pipBack:$('#photo-editor-pip-back'),pipSize:$('#photo-editor-pip-size'),pipSizeValue:$('#photo-editor-pip-size-value'),pipRotation:$('#photo-editor-pip-rotation'),pipRotationValue:$('#photo-editor-pip-rotation-value'),pipX:$('#photo-editor-pip-x'),pipXValue:$('#photo-editor-pip-x-value'),pipY:$('#photo-editor-pip-y'),pipYValue:$('#photo-editor-pip-y-value'),pipOpacity:$('#photo-editor-pip-opacity'),pipOpacityValue:$('#photo-editor-pip-opacity-value'),
  pipStrokeEnabled:$('#photo-editor-pip-stroke-enabled'),pipStrokeWidth:$('#photo-editor-pip-stroke-width'),pipStrokeWidthValue:$('#photo-editor-pip-stroke-width-value'),pipStrokeColor:$('#photo-editor-pip-stroke-color'),
  pipShadowEnabled:$('#photo-editor-pip-shadow-enabled'),pipShadowSize:$('#photo-editor-pip-shadow-size'),pipShadowSizeValue:$('#photo-editor-pip-shadow-size-value'),pipShadowBlur:$('#photo-editor-pip-shadow-blur'),pipShadowBlurValue:$('#photo-editor-pip-shadow-blur-value'),pipShadowColor:$('#photo-editor-pip-shadow-color'),pipShadowOpacity:$('#photo-editor-pip-shadow-opacity'),pipShadowOpacityValue:$('#photo-editor-pip-shadow-opacity-value'),pipShadowX:$('#photo-editor-pip-shadow-x'),pipShadowXValue:$('#photo-editor-pip-shadow-x-value'),pipShadowY:$('#photo-editor-pip-shadow-y'),pipShadowYValue:$('#photo-editor-pip-shadow-y-value'),clearPip:$('#photo-editor-clear-pip'),
  textLayers:$('#photo-editor-text-layers'),addText:$('#photo-editor-add-text'),removeText:$('#photo-editor-remove-text'),text:$('#photo-editor-text'),fontFamily:$('#photo-editor-font-family'),fontSize:$('#photo-editor-font-size'),textColor:$('#photo-editor-text-color'),textX:$('#photo-editor-text-x'),textXValue:$('#photo-editor-text-x-value'),textY:$('#photo-editor-text-y'),textYValue:$('#photo-editor-text-y-value'),textSpacing:$('#photo-editor-text-spacing'),textSpacingValue:$('#photo-editor-text-spacing-value'),textShadow:$('#photo-editor-text-shadow'),fontStatus:$('#photo-editor-font-status'),fontFile:$('#photo-editor-font-file'),saveTextDefaults:$('#photo-editor-save-text-defaults'),applyTextDefaults:$('#photo-editor-apply-text-defaults'),
  frameEnabled:$('#photo-editor-frame-enabled'),frameFile:$('#photo-editor-frame-file'),frameStatus:$('#photo-editor-frame-status'),clearFrame:$('#photo-editor-clear-frame'),size:$('#photo-editor-size'),format:$('#photo-editor-format'),qualityWrap:$('#photo-editor-quality-wrap'),quality:$('#photo-editor-quality'),qualityValue:$('#photo-editor-quality-value'),fileName:$('#photo-editor-file-name'),download:$('#photo-editor-download'),message:$('#photo-editor-message')
};
ui.canvas.width=PREVIEW_W;ui.canvas.height=PREVIEW_H;
const ctx=ui.canvas.getContext('2d',{alpha:false,desynchronized:true});
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
function hexAlpha(hex,alpha=1){const raw=String(hex||'#000000').replace('#','').trim(),full=raw.length===3?raw.split('').map(x=>x+x).join(''):raw,n=parseInt(full,16);if(!Number.isFinite(n))return`rgba(0,0,0,${alpha})`;return`rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${clamp(alpha,0,1)})`;}
function cleanTextDefaults(value={}){return{font:String(value.font||ORIGINAL_TEXT_DEFAULTS.font),size:clamp(+value.size||ORIGINAL_TEXT_DEFAULTS.size,40,500),color:/^#[0-9a-f]{6}$/i.test(value.color||'')?value.color:ORIGINAL_TEXT_DEFAULTS.color,x:clamp(+value.x||ORIGINAL_TEXT_DEFAULTS.x,5,95),y:clamp(+value.y||ORIGINAL_TEXT_DEFAULTS.y,8,94),spacing:clamp(+value.spacing||ORIGINAL_TEXT_DEFAULTS.spacing,70,180),shadow:value.shadow!==false};}
function readTextDefaults(){try{return cleanTextDefaults(JSON.parse(localStorage.getItem(TEXT_DEFAULTS_KEY)||'{}'));}catch{return{...ORIGINAL_TEXT_DEFAULTS};}}
let textDefaults=readTextDefaults();
let textSeq=0;
const newText=()=>({id:`text-${++textSeq}`,text:'',...textDefaults});
const firstText=newText();
const s={image:null,imageUrl:'',imageBlob:null,imageName:'',baseScale:1,zoom:1,x:W/2,y:H/2,rotation:0,flipX:1,brightness:100,contrast:100,saturation:100,pinchLocked:false,pips:[],activePipId:null,pipSeq:0,pipOverlayId:null,pipGesture:null,texts:[firstText],activeTextId:firstText.id,cffSelection:{type:'none',id:null},frameEnabled:true,frame:null,frameUrl:'',logo:null,fontReady:false,pointers:new Map(),dragId:null,pinch:null,renderQueued:false};
const activePip=()=>s.pips.find(p=>p.id===s.activePipId)||s.pips[s.pips.length-1]||null;
Object.defineProperties(s,{
  pip:{get(){return activePip()?.image||null},set(v){const p=activePip();if(p)p.image=v}},
  pipUrl:{get(){return activePip()?.url||''},set(v){const p=activePip();if(p)p.url=v}},
  pipEnabled:{get(){return activePip()?.enabled!==false},set(v){const p=activePip();if(p)p.enabled=!!v}},
  pipSize:{get(){return activePip()?.size??28},set(v){const p=activePip();if(p)p.size=Number(v)}},
  pipX:{get(){return activePip()?.x??75},set(v){const p=activePip();if(p)p.x=Number(v)}},
  pipY:{get(){return activePip()?.y??25},set(v){const p=activePip();if(p)p.y=Number(v)}},
  pipOpacity:{get(){return activePip()?.opacity??100},set(v){const p=activePip();if(p)p.opacity=Number(v)}}
});
window.__CFF_ADMIN_EDICAO_STATE__=s;
window.__CFF_ADMIN_EDICAO_QUEUE__=queue;
let initialized=false,officialFontFace=null;

function msg(t,type=''){ui.message.textContent=t||'';ui.message.classList.toggle('is-error',type==='error');ui.message.classList.toggle('is-success',type==='success');}
function queue(){if(s.renderQueued)return;s.renderQueued=true;requestAnimationFrame(()=>{s.renderQueued=false;render();});}
function rounded(c,x,y,w,h,r){r=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath();}
function background(c){const g=c.createLinearGradient(0,0,W,H);g.addColorStop(0,'#0b0d14');g.addColorStop(.56,'#12161d');g.addColorStop(1,'#020304');c.fillStyle=g;c.fillRect(0,0,W,H);c.save();c.globalAlpha=.16;const r=c.createRadialGradient(W*.5,H*.34,40,W*.5,H*.34,W*.48);r.addColorStop(0,'#f3c66a');r.addColorStop(.18,'rgba(243,198,106,.65)');r.addColorStop(.45,'rgba(243,198,106,.12)');r.addColorStop(1,'rgba(243,198,106,0)');c.fillStyle=r;c.fillRect(0,0,W,H);c.restore();}
function photo(c){if(!s.image)return;const sc=s.baseScale*s.zoom,w=s.image.naturalWidth*sc,h=s.image.naturalHeight*sc;c.save();c.filter=`brightness(${s.brightness}%) contrast(${s.contrast}%) saturate(${s.saturation}%)`;c.translate(s.x,s.y);c.rotate(s.rotation*Math.PI/180);c.scale(s.flipX,1);c.drawImage(s.image,-w/2,-h/2,w,h);c.restore();c.filter='none';}
function explicitLines(text){return String(text||'').replace(/\r/g,'').split('\n').slice(0,10);}
function fontCss(name,size){const weight=name==='Montserrat'?'900':'700';if(name==='Impact')return `${size}px Impact, "Arial Black", sans-serif`;return `${weight} ${size}px "${name}", Impact, "Arial Black", sans-serif`;}
function textLayer(c,layer){const text=String(layer.text||'');if(!text.trim())return;const size=clamp(+layer.size||190,40,500),x=W*(clamp(+layer.x||50,5,95)/100),y=H*(clamp(+layer.y||86,8,94)/100),lineH=size*(clamp(+layer.spacing||106,70,180)/100);c.save();c.textAlign='center';c.textBaseline='middle';c.font=fontCss(layer.font||FONT,size);c.fillStyle=layer.color||'#fff';if(layer.shadow){c.shadowColor='rgba(0,0,0,.62)';c.shadowBlur=Math.max(10,size*.08);c.shadowOffsetY=Math.max(4,size*.035);}const lines=explicitLines(text.toUpperCase()),start=y-((lines.length-1)*lineH)/2;lines.forEach((line,i)=>c.fillText(line,x,start+i*lineH));c.restore();}
function textLayers(c,exporting=false){if(!exporting)return;s.texts.forEach(layer=>textLayer(c,layer));}
function pipLayer(c,exporting=false){for(const p of s.pips){if(!p?.image||p.enabled===false||!exporting)continue;const ratio=(p.image.naturalWidth||p.image.width)/(p.image.naturalHeight||p.image.height||1),w=W*(clamp(p.size,3,180)/100),h=w/ratio,x=W*(Number(p.x)||0)/100,y=H*(Number(p.y)||0)/100;c.save();c.globalAlpha=clamp(p.opacity,0,100)/100;c.translate(x,y);c.rotate((Number(p.rotation)||0)*Math.PI/180);c.scale(p.flipX===-1?-1:1,1);if(p.shadowEnabled!==false&&!(window.__CFF_ADMIN_EDICAO_INTERACTING__&&!exporting)){const blur=clamp(Number(p.shadowBlur)||0,0,140),spread=clamp(Number(p.shadowSize)||0,0,80);c.shadowColor=hexAlpha(p.shadowColor||'#000000',clamp(Number(p.shadowOpacity??45),0,100)/100);c.shadowBlur=blur+spread*.65;c.shadowOffsetX=clamp(Number(p.shadowX)||0,-120,120);c.shadowOffsetY=clamp(Number(p.shadowY)||0,-120,120);}else{c.shadowColor='transparent';c.shadowBlur=0;c.shadowOffsetX=0;c.shadowOffsetY=0;}c.drawImage(p.image,-w/2,-h/2,w,h);c.shadowColor='transparent';c.shadowBlur=0;c.shadowOffsetX=0;c.shadowOffsetY=0;if(p.strokeEnabled&&Number(p.strokeWidth)>0){c.lineWidth=clamp(Number(p.strokeWidth)||0,0,40);c.strokeStyle=p.strokeColor||'#ffffff';c.strokeRect(-w/2,-h/2,w,h);}c.restore();}}
function brand(c){const x=W*.73,y=H*.89,ls=230;if(s.logo?.complete&&s.logo.naturalWidth){const r=s.logo.naturalWidth/s.logo.naturalHeight,lw=r>=1?ls:ls*r,lh=r>=1?ls/r:ls;c.drawImage(s.logo,x-lw-40,y-lh/2,lw,lh);}c.textAlign='left';c.textBaseline='alphabetic';c.fillStyle='#fff';c.shadowColor='rgba(0,0,0,.45)';c.shadowBlur=8;c.shadowOffsetY=3;c.font=fontCss(FONT,150);c.fillText('CENTRAL',x,y-18);c.font=fontCss(FONT,92);c.fillText('FREE FIRE',x,y+88);c.shadowColor='transparent';}
function defaultFrame(c){c.save();c.fillStyle='#fff';c.beginPath();c.moveTo(0,H*.655);c.bezierCurveTo(W*.08,H*.69,W*.24,H*.78,W*.39,H*.79);c.bezierCurveTo(W*.56,H*.80,W*.66,H*.75,W*.79,H*.78);c.bezierCurveTo(W*.88,H*.80,W*.94,H*.83,W,H*.85);c.lineTo(W,H);c.lineTo(0,H);c.closePath();c.fill();rounded(c,72,72,W-144,H-144,390);c.lineWidth=86;c.strokeStyle='#070707';c.stroke();c.lineWidth=56;c.strokeStyle='#fff';c.stroke();c.lineWidth=15;c.strokeStyle='#070707';c.stroke();c.fillStyle='#050505';c.beginPath();c.moveTo(W*.955,H*.84);c.lineTo(W*.955,H*.93);c.lineTo(W*.995,H*.915);c.lineTo(W*.995,H*.825);c.closePath();c.fill();brand(c);c.restore();}
function frame(c){if(!s.frameEnabled)return;if(s.frame)c.drawImage(s.frame,0,0,W,H);else defaultFrame(c);}
function renderScene(c,exporting=false){background(c);photo(c);frame(c);pipLayer(c,exporting);textLayers(c,exporting);}
function render(){const sx=ui.canvas.width/W,sy=ui.canvas.height/H;ctx.__cffEditorScene=true;ctx.__cffScaleX=sx;ctx.__cffScaleY=sy;ctx.setTransform(sx,0,0,sy,0,0);ctx.clearRect(0,0,W,H);renderScene(ctx,false);ctx.setTransform(1,0,0,1,0,0);const hasImage=!!s.image;ui.empty.hidden=hasImage;ui.empty.classList.toggle('is-hidden',hasImage);ui.download.disabled=!hasImage;if(ui.deleteMain)ui.deleteMain.disabled=!hasImage;const pinchText=s.pinchLocked?'pinça travada':'pinça para zoom';ui.status.textContent=hasImage?`${s.image.naturalWidth} × ${s.image.naturalHeight} • preview leve • arraste para mover • ${pinchText}`:'Adicione uma foto para começar';syncPipOverlays();}
function fit(mode='contain'){if(!s.image)return;const sx=W/s.image.naturalWidth,sy=H/s.image.naturalHeight;s.baseScale=mode==='contain'?Math.min(sx,sy):Math.max(sx,sy);s.zoom=1;s.x=W/2;const fittedH=s.image.naturalHeight*s.baseScale;s.y=mode==='contain'?fittedH/2:H/2;ui.zoom.value='100';ui.zoomValue.textContent='100%';queue();}
function loadPhoto(file){if(!file||!/^image\/(png|jpeg|webp)$/i.test(file.type)){msg('Escolha uma imagem PNG, JPG ou WEBP.','error');return;}if(s.imageUrl)URL.revokeObjectURL(s.imageUrl);const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{s.image=img;s.imageUrl=url;s.imageBlob=file;s.imageName=file.name||'foto';ui.imageName.textContent=s.imageName;if(ui.deleteMain)ui.deleteMain.disabled=false;s.rotation=0;s.flipX=1;ui.rotation.value='0';ui.rotationValue.textContent='0°';ui.empty.hidden=true;ui.empty.classList.add('is-hidden');fit('contain');window.__CFF_ADMIN_EDICAO_SELECT__?.('photo');window.dispatchEvent(new CustomEvent('cff-photo-changed',{detail:{blob:file,name:file.name}}));msg('Foto carregada. Ajuste no preview e exporte quando estiver pronta.','success');};img.onerror=()=>{URL.revokeObjectURL(url);msg('Não foi possível abrir essa imagem.','error');};img.src=url;}
function createPipRecord(img,url,name,blob,meta={}){let id=String(meta.id||'');if(id){const n=Number(id.match(/(\d+)$/)?.[1]||0);if(n)s.pipSeq=Math.max(s.pipSeq,n);}else id=`pip-${++s.pipSeq}`;return{id,image:img,url,name:String(meta.name||name||`P.I.P. ${s.pips.length+1}`),sourceBlob:blob||null,enabled:meta.enabled!==false,size:clamp(meta.size??28,3,180),x:Number.isFinite(Number(meta.x))?Number(meta.x):75,y:Number.isFinite(Number(meta.y))?Number(meta.y):25,opacity:clamp(meta.opacity??100,0,100),rotation:Number(meta.rotation)||0,flipX:meta.flipX===-1?-1:1,strokeEnabled:!!meta.strokeEnabled,strokeWidth:clamp(meta.strokeWidth??6,0,40),strokeColor:/^#[0-9a-f]{6}$/i.test(meta.strokeColor||'')?meta.strokeColor:'#ffffff',shadowEnabled:meta.shadowEnabled!==false,shadowSize:clamp(meta.shadowSize??10,0,80),shadowBlur:clamp(meta.shadowBlur??24,0,140),shadowColor:/^#[0-9a-f]{6}$/i.test(meta.shadowColor||'')?meta.shadowColor:'#000000',shadowOpacity:clamp(meta.shadowOpacity??45,0,100),shadowX:clamp(meta.shadowX??0,-120,120),shadowY:clamp(meta.shadowY??18,-120,120)};}
function loadPip(file,meta={}){if(!file||!/^image\/(png|jpeg|webp)$/i.test(file.type)){msg('Escolha uma imagem PNG, JPG ou WEBP para o P.I.P.','error');return Promise.resolve(null);}const url=URL.createObjectURL(file),img=new Image();return new Promise(resolve=>{img.onload=()=>{const p=createPipRecord(img,url,file.name,file,meta);s.pips.push(p);s.activePipId=p.id;renderPipTabs();syncPipControls();window.__CFF_ADMIN_EDICAO_SELECT__?.('pip',p.id);queue();window.dispatchEvent(new CustomEvent('cff-pips-changed',{detail:{type:'add',pip:p,blob:file}}));msg(`P.I.P. ${s.pips.length} adicionado. Arraste direto na arte.`,'success');resolve(p);};img.onerror=()=>{URL.revokeObjectURL(url);msg('Não foi possível abrir a imagem do P.I.P.','error');resolve(null);};img.src=url;});}
function clearPip(){const p=activePip();if(!p)return;try{if(p.url)URL.revokeObjectURL(p.url);}catch{}const id=p.id,wasSelected=s.cffSelection?.type==='pip'&&s.cffSelection?.id===id;s.pips=s.pips.filter(x=>x.id!==id);s.activePipId=s.pips[s.pips.length-1]?.id||null;ui.pipFile.value='';renderPipTabs();syncPipControls();if(wasSelected)window.__CFF_ADMIN_EDICAO_CLEAR_SELECTION__?.();queue();window.dispatchEvent(new CustomEvent('cff-pips-changed',{detail:{type:'remove',id}}));msg('P.I.P. removido.','success');}
function selectPip(id){if(!s.pips.some(p=>p.id===id))return;s.activePipId=id;renderPipTabs();syncPipControls();window.__CFF_ADMIN_EDICAO_SELECT__?.('pip',id);syncPipOverlays();}
function duplicatePip(){const p=activePip();if(!p?.sourceBlob)return msg('Não foi possível duplicar esta camada.','error');loadPip(p.sourceBlob,{size:p.size,x:p.x+3,y:p.y+3,opacity:p.opacity,rotation:p.rotation,flipX:p.flipX,enabled:p.enabled,strokeEnabled:p.strokeEnabled,strokeWidth:p.strokeWidth,strokeColor:p.strokeColor,shadowEnabled:p.shadowEnabled,shadowSize:p.shadowSize,shadowBlur:p.shadowBlur,shadowColor:p.shadowColor,shadowOpacity:p.shadowOpacity,shadowX:p.shadowX,shadowY:p.shadowY,name:`${p.name} cópia`});}
function movePipLayer(dir){const p=activePip();if(!p)return;const i=s.pips.findIndex(x=>x.id===p.id),j=clamp(i+dir,0,s.pips.length-1);if(i===j)return;const [item]=s.pips.splice(i,1);s.pips.splice(j,0,item);renderPipTabs();queue();window.dispatchEvent(new CustomEvent('cff-pips-changed',{detail:{type:'order'}}));}

function renderPipTabs(){if(!ui.pipLayers)return;ui.pipLayers.innerHTML='';s.pips.forEach((p,i)=>{const b=document.createElement('button');b.type='button';b.className='photo-editor-pip-layer'+(p.id===s.activePipId?' is-active':'')+(p.enabled===false?' is-hidden':'');b.textContent=`PIP ${i+1} · ${p.name||'imagem'}`;b.title=p.name||`P.I.P. ${i+1}`;b.addEventListener('click',()=>selectPip(p.id));ui.pipLayers.appendChild(b);});}
function syncPipControls(){const p=activePip(),has=!!p,count=s.pips.length;ui.pipStatus.textContent=count?`${count} P.I.P.${count===1?'':'s'}`:'Sem imagem';ui.pipStatus.classList.toggle('is-ready',count>0);const controls=[ui.pipEnabled,ui.pipSize,ui.pipRotation,ui.pipX,ui.pipY,ui.pipOpacity,ui.pipStrokeEnabled,ui.pipStrokeWidth,ui.pipStrokeColor,ui.pipShadowEnabled,ui.pipShadowSize,ui.pipShadowBlur,ui.pipShadowColor,ui.pipShadowOpacity,ui.pipShadowX,ui.pipShadowY,ui.clearPip,ui.duplicatePip,ui.pipFront,ui.pipBack];controls.forEach(el=>{if(el)el.disabled=!has});if(!p)return;if(ui.pipEnabled)ui.pipEnabled.checked=p.enabled!==false;if(ui.pipSize){ui.pipSize.value=String(p.size);ui.pipSizeValue.textContent=`${Number(p.size).toFixed(Number(p.size)%1?1:0)}%`;}if(ui.pipRotation){ui.pipRotation.value=String(p.rotation||0);ui.pipRotationValue.textContent=`${Math.round(p.rotation||0)}°`;}if(ui.pipX){ui.pipX.value=String(p.x);ui.pipXValue.textContent=`${Number(p.x).toFixed(1)}%`;}if(ui.pipY){ui.pipY.value=String(p.y);ui.pipYValue.textContent=`${Number(p.y).toFixed(1)}%`;}if(ui.pipOpacity){ui.pipOpacity.value=String(p.opacity);ui.pipOpacityValue.textContent=`${Math.round(p.opacity)}%`;}if(ui.pipStrokeEnabled)ui.pipStrokeEnabled.checked=!!p.strokeEnabled;if(ui.pipStrokeWidth){ui.pipStrokeWidth.value=String(p.strokeWidth);ui.pipStrokeWidthValue.textContent=`${Math.round(p.strokeWidth)} px`;}if(ui.pipStrokeColor)ui.pipStrokeColor.value=p.strokeColor||'#ffffff';if(ui.pipShadowEnabled)ui.pipShadowEnabled.checked=p.shadowEnabled!==false;if(ui.pipShadowSize){ui.pipShadowSize.value=String(p.shadowSize);ui.pipShadowSizeValue.textContent=`${Math.round(p.shadowSize)} px`;}if(ui.pipShadowBlur){ui.pipShadowBlur.value=String(p.shadowBlur);ui.pipShadowBlurValue.textContent=`${Math.round(p.shadowBlur)} px`;}if(ui.pipShadowColor)ui.pipShadowColor.value=p.shadowColor||'#000000';if(ui.pipShadowOpacity){ui.pipShadowOpacity.value=String(p.shadowOpacity);ui.pipShadowOpacityValue.textContent=`${Math.round(p.shadowOpacity)}%`;}if(ui.pipShadowX){ui.pipShadowX.value=String(p.shadowX);ui.pipShadowXValue.textContent=`${Math.round(p.shadowX)} px`;}if(ui.pipShadowY){ui.pipShadowY.value=String(p.shadowY);ui.pipShadowYValue.textContent=`${Math.round(p.shadowY)} px`;}}
function overlayForPip(id){return ui.stage.querySelector(`.photo-editor-pip-hit[data-pip-id="${CSS.escape(id)}"]`);}
function ensurePipOverlay(p,index){let el=overlayForPip(p.id);if(!el){el=document.createElement('div');el.className='photo-editor-pip-hit';el.dataset.pipId=p.id;el.innerHTML='<img class="photo-editor-pip-live" alt=""><span class="photo-editor-pip-name"></span><button class="photo-editor-pip-handle" data-corner="nw" type="button" aria-label="Redimensionar PIP"></button><button class="photo-editor-pip-handle" data-corner="ne" type="button" aria-label="Redimensionar PIP"></button><button class="photo-editor-pip-handle" data-corner="sw" type="button" aria-label="Redimensionar PIP"></button><button class="photo-editor-pip-handle" data-corner="se" type="button" aria-label="Redimensionar PIP"></button><span class="photo-editor-pip-rotate-line"></span><button class="photo-editor-pip-rotate" type="button" aria-label="Rotacionar PIP" title="Arraste para girar">↻</button>';el.addEventListener('pointerdown',e=>{const item=s.pips.find(x=>x.id===el.dataset.pipId);if(!item)return;const mode=e.target.closest('.photo-editor-pip-rotate')?'rotate':e.target.closest('.photo-editor-pip-handle')?'resize':'move';beginPipGesture(e,item,mode);},true);ui.stage.appendChild(el);}const img=el.querySelector('.photo-editor-pip-live'),name=el.querySelector('.photo-editor-pip-name'),ratio=(p.image?.naturalWidth||p.image?.width||1)/(p.image?.naturalHeight||p.image?.height||1),stageW=ui.stage.getBoundingClientRect().width||1,cssScale=stageW/W;if(img&&img.src!==p.url)img.src=p.url;if(name)name.textContent=p.name||`P.I.P. ${index+1}`;if(img){img.style.border=p.strokeEnabled&&Number(p.strokeWidth)>0?`${Math.max(.5,Number(p.strokeWidth)*cssScale)}px solid ${p.strokeColor||'#ffffff'}`:'0 solid transparent';img.style.boxSizing='border-box';if(p.shadowEnabled!==false){const blur=(Number(p.shadowBlur)||0)+(Number(p.shadowSize)||0)*.65,x=(Number(p.shadowX)||0)*cssScale,y=(Number(p.shadowY)||0)*cssScale,b=blur*cssScale;img.style.filter=`drop-shadow(${x}px ${y}px ${b}px ${hexAlpha(p.shadowColor||'#000000',clamp(Number(p.shadowOpacity??45),0,100)/100)})`;}else img.style.filter='none';el.style.setProperty('--pip-opacity',String(clamp(Number(p.opacity)||0,0,100)/100));}el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;el.style.width=`${p.size}%`;el.style.aspectRatio=String(ratio||1);el.style.transform=`translate(-50%,-50%) rotate(${Number(p.rotation)||0}deg)`;el.style.zIndex=String(42+index+(p.id===s.activePipId?40:0));el.hidden=p.enabled===false;const selected=s.cffSelection?.type==='pip'&&s.cffSelection?.id===p.id;el.classList.toggle('is-active',selected);el.classList.toggle('is-interacting',s.pipOverlayId===p.id);return el;}
function syncPipOverlays(){const ids=new Set(s.pips.map(p=>p.id));ui.stage.querySelectorAll('.photo-editor-pip-hit').forEach(el=>{if(!ids.has(el.dataset.pipId))el.remove();});s.pips.forEach((p,i)=>ensurePipOverlay(p,i));}
let pipVisualRaf=0;
function schedulePipVisual(){if(pipVisualRaf)return;pipVisualRaf=requestAnimationFrame(()=>{pipVisualRaf=0;syncPipControls();syncPipOverlays();});}
function beginPipGesture(e,p,mode){if(!p?.image)return;e.preventDefault();e.stopPropagation();selectPip(p.id);const r=ui.stage.getBoundingClientRect(),cx=r.left+(p.x/100)*r.width,cy=r.top+(p.y/100)*r.height;s.pipGesture={id:e.pointerId,pipId:p.id,mode,startClientX:e.clientX,startClientY:e.clientY,startX:p.x,startY:p.y,startSize:p.size,startRotation:Number(p.rotation)||0,centerX:cx,centerY:cy,startAngle:Math.atan2(e.clientY-cy,e.clientX-cx),startDist:Math.max(8,Math.hypot(e.clientX-cx,e.clientY-cy)),stageW:r.width,stageH:r.height};s.pipOverlayId=p.id;ensurePipOverlay(p,s.pips.indexOf(p))?.setPointerCapture?.(e.pointerId);window.__CFF_ADMIN_EDICAO_INTERACTING__=true;window.dispatchEvent(new CustomEvent('cff-editor-interaction-start'));queue();window.addEventListener('pointermove',onPipPointerMove,{capture:true});window.addEventListener('pointerup',endPipGesture,{capture:true,once:true});window.addEventListener('pointercancel',endPipGesture,{capture:true,once:true});}
function onPipPointerMove(e){const g=s.pipGesture;if(!g||e.pointerId!==g.id)return;const p=s.pips.find(x=>x.id===g.pipId);if(!p)return;e.preventDefault();e.stopPropagation();if(g.mode==='move'){p.x=g.startX+((e.clientX-g.startClientX)/g.stageW)*100;p.y=g.startY+((e.clientY-g.startClientY)/g.stageH)*100;}else if(g.mode==='resize'){const d=Math.max(8,Math.hypot(e.clientX-g.centerX,e.clientY-g.centerY));p.size=clamp(g.startSize*(d/g.startDist),3,180);}else if(g.mode==='rotate'){const angle=Math.atan2(e.clientY-g.centerY,e.clientX-g.centerX);let deg=g.startRotation+(angle-g.startAngle)*180/Math.PI;if(e.shiftKey)deg=Math.round(deg/15)*15;while(deg>180)deg-=360;while(deg<-180)deg+=360;p.rotation=deg;}schedulePipVisual();}
function endPipGesture(e){const g=s.pipGesture;if(!g||e.pointerId!==g.id)return;e.preventDefault();e.stopPropagation();s.pipGesture=null;s.pipOverlayId=null;window.removeEventListener('pointermove',onPipPointerMove,true);window.__CFF_ADMIN_EDICAO_INTERACTING__=false;window.dispatchEvent(new CustomEvent('cff-editor-interaction-end'));syncPipControls();syncPipOverlays();queue();window.dispatchEvent(new CustomEvent('cff-pips-changed',{detail:{type:'update',id:g.pipId}}));}
function updateActivePipFromControl(key,value){const p=activePip();if(!p)return;p[key]=value;syncPipControls();syncPipOverlays();queue();}
async function pasteImageFromClipboard(){if(!navigator.clipboard?.read){msg('Use Ctrl+V / Cmd+V para colar a imagem neste navegador.','error');return;}try{const items=await navigator.clipboard.read();for(const item of items){const type=item.types.find(t=>/^image\//i.test(t));if(!type)continue;const blob=await item.getType(type),file=new File([blob],`colado-${Date.now()}.png`,{type:blob.type||type});if(!s.image)loadPhoto(file);else await loadPip(file);return;}msg('Não encontrei uma imagem na área de transferência.','error');}catch{msg('O navegador bloqueou o botão. Use Ctrl+V / Cmd+V para colar.','error');}}
function onPaste(e){const item=[...(e.clipboardData?.items||[])].find(x=>x.kind==='file'&&/^image\//i.test(x.type));if(!item)return;const blob=item.getAsFile();if(!blob)return;e.preventDefault();const file=blob instanceof File?blob:new File([blob],`colado-${Date.now()}.png`,{type:blob.type||'image/png'});if(!s.image)loadPhoto(file);else loadPip(file);}
function onEditorKeydown(e){const p=activePip();if(!p||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName||''))return;e.preventDefault();const step=e.shiftKey?1:.1;if(e.key==='ArrowLeft')p.x-=step;if(e.key==='ArrowRight')p.x+=step;if(e.key==='ArrowUp')p.y-=step;if(e.key==='ArrowDown')p.y+=step;syncPipControls();syncPipOverlays();queue();window.dispatchEvent(new CustomEvent('cff-pips-changed',{detail:{type:'update',id:p.id}}));}
window.__CFF_ADMIN_EDICAO_ADD_PIP_BLOB__=(blob,meta={})=>{const file=blob instanceof File?blob:new File([blob],meta.name||`pip-${Date.now()}.png`,{type:blob.type||'image/png'});return loadPip(file,meta);};
window.__CFF_ADMIN_EDICAO_SYNC_PIPS__=()=>{renderPipTabs();syncPipControls();syncPipOverlays();queue();};
function clearMainPhoto(){try{if(s.imageUrl)URL.revokeObjectURL(s.imageUrl);}catch{}s.image=null;s.imageUrl='';s.imageBlob=null;s.imageName='';s.baseScale=1;s.zoom=1;s.x=W/2;s.y=H/2;s.rotation=0;s.flipX=1;ui.file.value='';ui.imageName.textContent='Nenhuma foto';ui.rotation.value='0';ui.rotationValue.textContent='0°';ui.zoom.value='100';ui.zoomValue.textContent='100%';ui.empty.hidden=false;ui.empty.classList.remove('is-hidden');ui.download.disabled=true;if(ui.deleteMain)ui.deleteMain.disabled=true;window.__CFF_ADMIN_EDICAO_CLEAR_SELECTION__?.();queue();window.dispatchEvent(new CustomEvent('cff-photo-removed'));msg('Foto principal removida.','success');}
function requestDeleteMainPhoto(){if(!s.image)return;if(ui.deleteMainDialog?.showModal)ui.deleteMainDialog.showModal();else if(confirm('Remover a foto principal? P.I.P.s, textos e moldura serão mantidos.'))clearMainPhoto();}
window.__CFF_ADMIN_EDICAO_CONFIRM_DELETE_MAIN__=requestDeleteMainPhoto;
function resetAdjust(){s.brightness=s.contrast=s.saturation=100;for(const [el,out] of [[ui.brightness,ui.brightnessValue],[ui.contrast,ui.contrastValue],[ui.saturation,ui.saturationValue]]){el.value='100';out.textContent='100%';}queue();}
function activeText(){return s.texts.find(x=>x.id===s.activeTextId)||s.texts[0];}
function renderTextTabs(){ui.textLayers.innerHTML='';s.texts.forEach((layer,i)=>{const b=document.createElement('button');b.type='button';b.className='photo-editor-text-layer'+(layer.id===s.activeTextId?' is-active':'');b.textContent=`Texto ${i+1}`;b.dataset.textId=layer.id;b.addEventListener('click',()=>{s.activeTextId=layer.id;renderTextTabs();syncTextControls();window.__CFF_ADMIN_EDICAO_SELECT__?.('text',layer.id);});ui.textLayers.appendChild(b);});ui.removeText.disabled=s.texts.length<=1;}
window.__CFF_ADMIN_EDICAO_ACTIVATE_TEXT__=id=>{const layer=s.texts.find(t=>t.id===id);if(!layer)return false;s.activeTextId=id;renderTextTabs();syncTextControls();return true;};
function syncTextControls(){const t=activeText();if(!t)return;ui.text.value=t.text;ui.fontFamily.value=t.font;ui.fontSize.value=String(t.size);ui.textColor.value=t.color;ui.textX.value=String(t.x);ui.textXValue.textContent=`${t.x}%`;ui.textY.value=String(t.y);ui.textYValue.textContent=`${t.y}%`;ui.textSpacing.value=String(t.spacing);ui.textSpacingValue.textContent=`${t.spacing}%`;ui.textShadow.checked=!!t.shadow;}
async function ensureFont(name){if(name===FONT){await loadOfficialFont();queue();return;}try{await document.fonts.load(fontCss(name,190));queue();}catch{queue();}}
function addText(){if(s.texts.length>=5){msg('Você pode usar até 5 camadas de texto.','error');return;}const t=newText();s.texts.push(t);s.activeTextId=t.id;renderTextTabs();syncTextControls();window.__CFF_ADMIN_EDICAO_SELECT__?.('text',t.id);ensureFont(t.font);queue();}
function removeText(){if(s.texts.length<=1)return;const removed=s.activeTextId,index=s.texts.findIndex(x=>x.id===removed);s.texts.splice(Math.max(index,0),1);s.activeTextId=s.texts[Math.max(0,index-1)]?.id||s.texts[0].id;renderTextTabs();syncTextControls();if(s.cffSelection?.type==='text'&&s.cffSelection?.id===removed)window.__CFF_ADMIN_EDICAO_CLEAR_SELECTION__?.();queue();}
window.__CFF_ADMIN_EDICAO_REMOVE_PIP__=clearPip;
window.__CFF_ADMIN_EDICAO_REMOVE_TEXT__=removeText;
function resetTexts(){textSeq=0;const t=newText();s.texts=[t];s.activeTextId=t.id;renderTextTabs();syncTextControls();ensureFont(t.font);}
function saveTextDefaults(){const t=activeText();if(!t)return;textDefaults=cleanTextDefaults(t);localStorage.setItem(TEXT_DEFAULTS_KEY,JSON.stringify(textDefaults));msg('Parâmetros deste texto salvos como padrão. Novos textos já vão nascer assim.','success');}
function applyTextDefaults(){const t=activeText();if(!t)return;Object.assign(t,textDefaults);syncTextControls();ensureFont(t.font);queue();msg('Padrão aplicado ao texto atual.','success');}
function resetAll(){s.rotation=0;s.flipX=1;s.pinchLocked=false;const p=activePip();if(p){p.size=28;p.x=75;p.y=25;p.opacity=100;p.rotation=0;p.enabled=true;p.strokeEnabled=false;p.strokeWidth=6;p.strokeColor='#ffffff';p.shadowEnabled=true;p.shadowSize=10;p.shadowBlur=24;p.shadowColor='#000000';p.shadowOpacity=45;p.shadowX=0;p.shadowY=18;}ui.rotation.value='0';ui.rotationValue.textContent='0°';syncPipControls();syncPipOverlays();syncPinchLock();resetTexts();resetAdjust();if(s.image)fit('contain');else queue();msg('Ajustes resetados.','success');}
function point(e){const r=ui.stage.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H};}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function mid(a,b){return{x:(a.x+b.x)/2,y:(a.y+b.y)/2}}
function syncZoom(){const p=Math.round(s.zoom*100);ui.zoom.value=String(p);ui.zoomValue.textContent=`${p}%`;}
function syncPinchLock(){ui.pinchLock.textContent=s.pinchLocked?'🔒 Pinça':'🔓 Pinça';ui.pinchLock.setAttribute('aria-pressed',String(s.pinchLocked));ui.pinchLock.classList.toggle('is-locked',s.pinchLocked);queue();}
function beginPinch(){if(s.pinchLocked)return;const pts=[...s.pointers.values()];if(pts.length<2)return;const [a,b]=pts,m=mid(a,b);s.dragId=null;s.pinch={distance:Math.max(dist(a,b),1),zoom:s.zoom,cx:m.x,cy:m.y,x:s.x,y:s.y};}
function down(e){if(!s.image)return;e.preventDefault();const p=point(e);s.pointers.set(e.pointerId,p);ui.stage.setPointerCapture?.(e.pointerId);if(s.pointers.size===1){s.dragId=e.pointerId;s.last=p;s.pinch=null;}else if(s.pinchLocked){s.dragId=null;s.pinch=null;}else beginPinch();}
function move(e){if(!s.pointers.has(e.pointerId))return;e.preventDefault();const p=point(e);s.pointers.set(e.pointerId,p);if(s.pointers.size>=2){if(s.pinchLocked)return;if(!s.pinch)beginPinch();const [a,b]=[...s.pointers.values()],m=mid(a,b);s.zoom=clamp(s.pinch.zoom*(Math.max(dist(a,b),1)/s.pinch.distance),.25,3);s.x=s.pinch.x+(m.x-s.pinch.cx);s.y=s.pinch.y+(m.y-s.pinch.cy);syncZoom();queue();return;}if(s.dragId===e.pointerId){s.x+=p.x-s.last.x;s.y+=p.y-s.last.y;s.last=p;queue();}}
function up(e){s.pointers.delete(e.pointerId);ui.stage.releasePointerCapture?.(e.pointerId);if(s.pointers.size>=2&&!s.pinchLocked){beginPinch();return;}s.pinch=null;if(s.pointers.size===1){const [id,p]=[...s.pointers.entries()][0];s.dragId=id;s.last=p;}else s.dragId=null;}
function filename(v){return String(v||'central-free-fire-edit').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,80)||'central-free-fire-edit';}
function download(){if(!s.image){msg('Adicione uma foto antes de exportar.','error');return;}const [w,h]=ui.size.value.split('x').map(Number),out=document.createElement('canvas');out.width=w;out.height=h;const c=out.getContext('2d',{alpha:false});c.imageSmoothingEnabled=true;c.imageSmoothingQuality='high';const sx=w/W,sy=h/H;c.__cffEditorScene=true;c.__cffScaleX=sx;c.__cffScaleY=sy;c.setTransform(sx,0,0,sy,0,0);c.clearRect(0,0,W,H);renderScene(c,true);c.setTransform(1,0,0,1,0,0);const jpg=ui.format.value==='jpg',mime=jpg?'image/jpeg':'image/png',q=jpg?clamp(+ui.quality.value/100,.6,1):undefined,name=`${filename(ui.fileName.value)}-${w}x${h}.${jpg?'jpg':'png'}`;ui.download.disabled=true;ui.download.textContent='Gerando...';out.toBlob(blob=>{ui.download.disabled=false;ui.download.textContent='Baixar arte';if(!blob){msg('Não foi possível gerar o arquivo.','error');return;}const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);msg(`Arte exportada em ${w} × ${h}.`,'success');},mime,q);}
function fontStatus(){ui.fontStatus.textContent=s.fontReady?'Avilock oficial ativa':'Avilock indisponível';ui.fontStatus.classList.toggle('is-ready',s.fontReady);ui.fontStatus.classList.toggle('is-warning',!s.fontReady);}
function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error);});}
async function dbPut(blob,key=FRAME_KEY){try{const db=await openDb();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(blob,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();}catch(e){console.warn(e)}}
async function dbGet(key=FRAME_KEY){try{const db=await openDb(),v=await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readonly'),q=tx.objectStore(STORE).get(key);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)});db.close();return v;}catch{return null}}
async function dbDelete(key=FRAME_KEY){try{const db=await openDb();await new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)});db.close();}catch{}}
async function loadOfficialFont(){if(officialFontFace){s.fontReady=true;fontStatus();return true;}try{const response=await fetch(OFFICIAL_FONT_URL,{cache:'no-store'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const buffer=await response.arrayBuffer(),face=new FontFace(FONT,buffer,{weight:'700',style:'normal'});await face.load();document.fonts.add(face);officialFontFace=face;s.fontReady=true;fontStatus();queue();return true;}catch(error){console.error('[Editor] Avilock oficial:',error);try{await document.fonts.load(fontCss(FONT,190));s.fontReady=document.fonts.check(fontCss(FONT,190));}catch{s.fontReady=false;}fontStatus();queue();return s.fontReady;}}
async function loadFontBlob(blob,persist=true){if(!blob)return false;try{const buffer=await blob.arrayBuffer(),face=new FontFace(FONT,buffer);await face.load();document.fonts.add(face);s.fontReady=true;if(persist)await dbPut(blob,FONT_KEY);fontStatus();queue();if(persist)msg('Fonte carregada neste navegador.','success');return true;}catch(error){console.error(error);s.fontReady=false;fontStatus();if(persist)msg('Não consegui carregar esse arquivo da fonte.','error');return false;}}
function frameStatus(t){ui.frameStatus.textContent=t;ui.frameStatus.classList.add('is-ready');}
function loadFrame(blob,persist=true){if(!blob)return;if(s.frameUrl)URL.revokeObjectURL(s.frameUrl);const url=URL.createObjectURL(blob),img=new Image();img.onload=async()=>{s.frame=img;s.frameUrl=url;frameStatus('Frente personalizada');if(persist)await dbPut(blob,FRAME_KEY);queue();msg('Imagem da frente aplicada por cima da foto.','success');};img.onerror=()=>{URL.revokeObjectURL(url);msg('Não foi possível abrir essa moldura.','error');};img.src=url;}
async function clearFrame(){if(s.frameUrl)URL.revokeObjectURL(s.frameUrl);s.frame=null;s.frameUrl='';ui.frameFile.value='';await dbDelete(FRAME_KEY);frameStatus('Padrão');queue();msg('Moldura padrão restaurada.','success');}
function syncAllEditorUi(){
  ui.imageName.textContent=s.image?s.imageName||'Foto principal':'Nenhuma foto';
  if(ui.deleteMain)ui.deleteMain.disabled=!s.image;
  ui.zoom.value=String(Math.round((Number(s.zoom)||1)*100));ui.zoomValue.textContent=`${Math.round((Number(s.zoom)||1)*100)}%`;
  ui.rotation.value=String(Math.round(Number(s.rotation)||0));ui.rotationValue.textContent=`${Math.round(Number(s.rotation)||0)}°`;
  for(const [el,out,key] of [[ui.brightness,ui.brightnessValue,'brightness'],[ui.contrast,ui.contrastValue,'contrast'],[ui.saturation,ui.saturationValue,'saturation']]){el.value=String(s[key]??100);out.textContent=`${s[key]??100}%`;}
  ui.frameEnabled.checked=s.frameEnabled!==false;
  renderTextTabs();syncTextControls();renderPipTabs();syncPipControls();syncPipOverlays();syncPinchLock();queue();
}
window.__CFF_ADMIN_EDICAO_SYNC_ALL__=syncAllEditorUi;
function bind(){
  ui.file.addEventListener('change',()=>loadPhoto(ui.file.files?.[0]));ui.resetAll.addEventListener('click',resetAll);ui.fitCover.addEventListener('click',()=>fit('cover'));ui.fitContain.addEventListener('click',()=>fit('contain'));ui.center.addEventListener('click',()=>{s.x=W/2;s.y=H/2;queue()});ui.flip.addEventListener('click',()=>{s.flipX*=-1;queue()});ui.zoom.addEventListener('input',()=>{s.zoom=clamp(+ui.zoom.value/100,.25,3);syncZoom();queue()});ui.pinchLock.addEventListener('click',()=>{s.pinchLocked=!s.pinchLocked;s.pinch=null;syncPinchLock();});ui.rotation.addEventListener('input',()=>{s.rotation=+ui.rotation.value;ui.rotationValue.textContent=`${s.rotation}°`;queue()});
  for(const [el,out,key] of [[ui.brightness,ui.brightnessValue,'brightness'],[ui.contrast,ui.contrastValue,'contrast'],[ui.saturation,ui.saturationValue,'saturation']])el.addEventListener('input',()=>{s[key]=+el.value;out.textContent=`${s[key]}%`;queue()});ui.resetAdjustments.addEventListener('click',resetAdjust);
  ui.pipFile.addEventListener('change',()=>{const files=[...(ui.pipFile.files||[])];files.forEach(f=>loadPip(f));ui.pipFile.value='';});
  ui.pipEnabled.addEventListener('change',()=>{const p=activePip();if(!p)return;p.enabled=ui.pipEnabled.checked;renderPipTabs();syncPipOverlays();queue();});
  ui.pipSize.addEventListener('input',()=>updateActivePipFromControl('size',clamp(+ui.pipSize.value,3,180)));
  ui.pipRotation.addEventListener('input',()=>updateActivePipFromControl('rotation',+ui.pipRotation.value));
  ui.pipX.addEventListener('input',()=>updateActivePipFromControl('x',+ui.pipX.value));
  ui.pipY.addEventListener('input',()=>updateActivePipFromControl('y',+ui.pipY.value));
  ui.pipOpacity.addEventListener('input',()=>updateActivePipFromControl('opacity',clamp(+ui.pipOpacity.value,0,100)));
  ui.pipStrokeEnabled?.addEventListener('change',()=>updateActivePipFromControl('strokeEnabled',ui.pipStrokeEnabled.checked));
  ui.pipStrokeWidth?.addEventListener('input',()=>updateActivePipFromControl('strokeWidth',clamp(+ui.pipStrokeWidth.value,0,40)));
  ui.pipStrokeColor?.addEventListener('input',()=>updateActivePipFromControl('strokeColor',ui.pipStrokeColor.value));
  ui.pipShadowEnabled?.addEventListener('change',()=>updateActivePipFromControl('shadowEnabled',ui.pipShadowEnabled.checked));
  ui.pipShadowSize?.addEventListener('input',()=>updateActivePipFromControl('shadowSize',clamp(+ui.pipShadowSize.value,0,80)));
  ui.pipShadowBlur?.addEventListener('input',()=>updateActivePipFromControl('shadowBlur',clamp(+ui.pipShadowBlur.value,0,140)));
  ui.pipShadowColor?.addEventListener('input',()=>updateActivePipFromControl('shadowColor',ui.pipShadowColor.value));
  ui.pipShadowOpacity?.addEventListener('input',()=>updateActivePipFromControl('shadowOpacity',clamp(+ui.pipShadowOpacity.value,0,100)));
  ui.pipShadowX?.addEventListener('input',()=>updateActivePipFromControl('shadowX',clamp(+ui.pipShadowX.value,-120,120)));
  ui.pipShadowY?.addEventListener('input',()=>updateActivePipFromControl('shadowY',clamp(+ui.pipShadowY.value,-120,120)));
  ui.clearPip.addEventListener('click',clearPip);ui.duplicatePip?.addEventListener('click',duplicatePip);ui.pipFront?.addEventListener('click',()=>movePipLayer(1));ui.pipBack?.addEventListener('click',()=>movePipLayer(-1));ui.pasteImage?.addEventListener('click',pasteImageFromClipboard);ui.addPipTop?.addEventListener('click',()=>ui.pipFile.click());ui.deleteMain?.addEventListener('click',requestDeleteMainPhoto);ui.confirmDeleteMain?.addEventListener('click',clearMainPhoto);document.addEventListener('paste',onPaste);ui.stage.addEventListener('keydown',onEditorKeydown);
  ui.addText.addEventListener('click',addText);ui.removeText.addEventListener('click',removeText);ui.text.addEventListener('input',()=>{activeText().text=ui.text.value;queue()});ui.fontFamily.addEventListener('change',()=>{activeText().font=ui.fontFamily.value;ensureFont(ui.fontFamily.value);queue()});ui.fontSize.addEventListener('input',()=>{activeText().size=clamp(+ui.fontSize.value||190,40,500);queue()});ui.textColor.addEventListener('input',()=>{activeText().color=ui.textColor.value;queue()});ui.textX.addEventListener('input',()=>{activeText().x=+ui.textX.value;ui.textXValue.textContent=`${activeText().x}%`;queue()});ui.textY.addEventListener('input',()=>{activeText().y=+ui.textY.value;ui.textYValue.textContent=`${activeText().y}%`;queue()});ui.textSpacing.addEventListener('input',()=>{activeText().spacing=+ui.textSpacing.value;ui.textSpacingValue.textContent=`${activeText().spacing}%`;queue()});ui.textShadow.addEventListener('change',()=>{activeText().shadow=ui.textShadow.checked;queue()});ui.saveTextDefaults.addEventListener('click',saveTextDefaults);ui.applyTextDefaults.addEventListener('click',applyTextDefaults);ui.fontFile.addEventListener('change',()=>{const f=ui.fontFile.files?.[0];if(!f)return;loadFontBlob(f,true)});
  ui.frameEnabled.addEventListener('change',()=>{s.frameEnabled=ui.frameEnabled.checked;queue()});ui.frameFile.addEventListener('change',()=>{const f=ui.frameFile.files?.[0];if(!f||!/^image\/(png|webp)$/i.test(f.type)){msg('Escolha uma moldura PNG ou WEBP.','error');return;}loadFrame(f)});ui.clearFrame.addEventListener('click',clearFrame);
  for(const [ev,fn] of [['pointerdown',down],['pointermove',move],['pointerup',up],['pointercancel',up],['pointerleave',up]])ui.stage.addEventListener(ev,fn);ui.stage.addEventListener('wheel',e=>{if(!s.image)return;e.preventDefault();s.zoom=clamp(s.zoom+(e.deltaY<0?.05:-.05),.25,3);syncZoom();queue()},{passive:false});ui.format.addEventListener('change',()=>ui.qualityWrap.hidden=ui.format.value!=='jpg');ui.quality.addEventListener('input',()=>ui.qualityValue.textContent=`${ui.quality.value}%`);ui.download.addEventListener('click',download);
}
async function init(){if(initialized)return;initialized=true;bind();renderTextTabs();syncTextControls();renderPipTabs();syncPipControls();syncPipOverlays();syncPinchLock();const logo=new Image();logo.onload=()=>{s.logo=logo;queue()};logo.src='central free fire.webp';await dbDelete(FONT_KEY);await loadOfficialFont();const savedFrame=await dbGet(FRAME_KEY);if(savedFrame)loadFrame(savedFrame,false);else frameStatus('Padrão');render();}
onAuthStateChanged(auth,async user=>{if(!user||String(user.email||'').toLowerCase()!==ADMIN_EMAIL){location.replace('admin.html');return;}ui.authMessage.hidden=true;ui.app.hidden=false;await init();});