const fs=require('fs'),vm=require('vm'),assert=require('assert'),C=require('../camp-notifications-core');
let data={},sends=[],fails=false,clock=Date.now();const copy=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
const read=p=>p.split('/').filter(Boolean).reduce((v,k)=>v?.[k],data)??null;
function write(p,v){const keys=p.split('/').filter(Boolean);let node=data;if(!keys.length){data=copy(v);return;}keys.slice(0,-1).forEach(k=>node=node[k]||(node[k]={}));if(v===null)delete node[keys.at(-1)];else node[keys.at(-1)]=copy(v);}
function ref(p='',q={}){return {child:s=>ref(p+'/'+s),get:async()=>{let value=read(p);if(q.limit&&value){value=Object.fromEntries(Object.entries(value).sort((a,b)=>a[1].at-b[1].at).slice(-q.limit));}return {val:()=>copy(value),exists:()=>value!==null};},set:async v=>write(p,v),remove:async()=>write(p,null),update:async obj=>{for(const [k,v]of Object.entries(obj))write(p+'/'+k,v);},transaction:async fn=>{const next=fn(copy(read(p)));const committed=next!==undefined;if(committed)write(p,next);return {committed,snapshot:{val:()=>copy(read(p))}};},orderByChild:()=>ref(p,q),limitToLast:limit=>ref(p,{...q,limit})};}
const handlers={};const fakeDate=class extends Date{static now(){return clock;}};
vm.runInNewContext(fs.readFileSync(require('path').join(__dirname,'../camp-notifications.js'),'utf8'),{exports:handlers,Date:fakeDate,console,URL,require:name=>name.endsWith('core')?C:name==='web-push'?{generateVAPIDKeys:()=>({publicKey:'pub',privateKey:'priv'}),sendNotification:async(s,p)=>{if(fails)throw {statusCode:410};sends.push({s,p:JSON.parse(p)});}}:name.endsWith('/https')?{onRequest:(opts,fn)=>fn}:name.endsWith('/database')&&name.startsWith('firebase-functions')?{onValueCreated:(opts,fn)=>fn,onValueWritten:(opts,fn)=>fn}:name.endsWith('/database')?{getDatabase:()=>({ref})}:{getAuth:()=>({verifyIdToken:async token=>({uid:token,email:token==='admin'?'admin@centralfreefire.com.br':'user@example.com'})})}});
async function api(uid,action,body={}){let status=200,value;await handlers.campNotificationApi({method:'POST',body:{action,...body},get:k=>k==='authorization'?(uid?'Bearer '+uid:''):''},{set(){},status(n){status=n;return this;},json(v){value=v;return this;}});return {status,...value};}
async function deliver(id){await handlers.campNotificationDeliver({params:{eventId:id},data:{val:()=>copy(read('campNotifications/private/events/'+id))}});}
async function official(value){await handlers.campNotificationOfficial({params:{stage:'final',day:'2',drop:'17'},data:{after:{exists:()=>!!value,val:()=>value}}});}
(async()=>{
 assert.equal((await api(null,'settings')).status,401);assert.equal((await api('alice','configure',{})).status,403);
 const t={tournamentId:'ffws-final',name:'FFWS Final',enabled:false,officialStage:'final',teams:[{id:'fx',name:'FLUXO W7M',aliases:['FLUXO']},{id:'loud',name:'LOUD SNICKERS',aliases:['LOUD']}]};assert((await api('admin','configure',t)).ok);
 const result={teamId:'fx',team:'Spoof',position:5,kills:8,points:14};assert.equal((await api('admin','publish',{tournamentId:t.tournamentId,day:2,drop:17,result})).status,400);
 t.enabled=true;assert((await api('admin','configure',t)).ok);assert((await api('alice','preferences',{tournamentId:t.tournamentId,enabled:true,all:false,teams:['fx']})).ok);await api('bob','preferences',{tournamentId:t.tournamentId,enabled:true,all:false,teams:['loud']});await api('carol','preferences',{tournamentId:t.tournamentId,enabled:true,all:true});await api('off','preferences',{tournamentId:t.tournamentId,enabled:false,all:true});
 const sub={endpoint:'https://fcm.googleapis.com/fcm/send/abc',keys:{p256dh:'a'.repeat(87),auth:'b'.repeat(22)}};assert((await api('alice','device',{subscription:sub})).ok);assert.equal((await api('alice','device',{subscription:{...sub,endpoint:'https://127.0.0.1/internal'}})).status,400);
 let r=await api('admin','publish',{tournamentId:t.tournamentId,day:2,drop:17,result});assert(r.ok&&!r.duplicate);r=await api('admin','publish',{tournamentId:t.tournamentId,day:2,drop:17,result:{...result,kills:9,points:15}});assert(r.duplicate);assert.equal((await api('alice','publish',{tournamentId:t.tournamentId,day:2,drop:17,result})).status,403);
 const id=C.eventId(t.tournamentId,2,17,'fx','partial');await Promise.all([deliver(id),deliver(id)]);await deliver(id);
 assert.equal(sends.length,1);assert.equal(sends[0].p.body.includes('Pontuação parcial'),true);assert(!read('campNotifications/inboxes/bob'));assert(!read('campNotifications/inboxes/off'));assert(read('campNotifications/inboxes/carol'));const inboxId=C.eventId(t.tournamentId,2,17,'fx','result');assert.equal(read('campNotifications/inboxes/alice/'+inboxId).team,'FLUXO W7M');
 const good={source:{teams:'T1.png',players:'P1.png'},teams:[{team:'FLUXO',position:4,kills:10,points:17}],players:[{team:'FLUXO',kills:6},{team:'FLUXO',kills:4}]};await official({...good,manual:true});await official({...good,testMode:true});await official({...good,players:[]});await official({...good,players:[{team:'FLUXO',kills:9}]});const offId=C.eventId(t.tournamentId,2,17,'fx','official');assert(!read('campNotifications/private/events/'+offId));await official(good);assert(read('campNotifications/private/events/'+offId));await deliver(offId);assert.equal(sends.length,2);assert.equal(read('campNotifications/inboxes/alice/'+inboxId).status,'official');assert.equal(Object.keys(read('campNotifications/inboxes/alice')).length,1);
 // Redelivery and T1/P1 corrections keep one inbox item and one official push.
 clock+=1000;await official({...good,teams:[{team:'FLUXO',position:3,kills:10,points:18}]});await deliver(offId);await deliver(id);assert.equal(sends.length,2);assert.equal(read('campNotifications/inboxes/alice/'+inboxId).points,18);
 // Self test only, throttled, and failed pushes expire safely.
 clock+=61000;const test=await api('alice','test');assert(test.ok&&test.accepted===1);assert.equal((await api('alice','test')).status,400);assert.equal(read('campNotifications/inboxes/bob'),null);
 clock+=61000;fails=true;assert((await api('alice','test')).ok);assert.equal(Object.keys(read('campNotifications/private/devices/alice')).length,0);
 console.log('PASS admin opt-in, account/team filters, no duplicates under concurrent delivery, partial/official transition, corrections, day2/drop17, private self-test, throttling, endpoint validation and expired devices');
})().catch(e=>{console.error(e);process.exit(1)});
