import {getApps} from 'https://www.gstatic.com/firebasejs/10.11.0/firebase-app.js';
import {getDatabase,ref,get} from 'https://www.gstatic.com/firebasejs/10.11.0/firebase-database.js';
import {request,stylesheet} from '/js/camp-notifications.js?v=20261007-v1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,80);
const app=()=>getApps().find(a=>a.name==='[DEFAULT]')||getApps()[0];
function snapshot(){const b=window.collectBackupData?.(true);if(!b?.selectedTeams?.length)throw Error('Adicione os times antes de configurar avisos.');return b;}
function identity(b){const stage=b.config?.cffFfwsStage,name=String(b.tournamentModeV1?.name||b.config?.tournamentName||'').trim();if(!name)throw Error('Defina o nome do torneio.');return {name,stage:['final','segundaFase'].includes(stage)?stage:'',id:['final','segundaFase'].includes(stage)?'ffws-br-2026-s2-'+stage.toLowerCase():''};}
function roster(b){const catalog=String(b.teams||'').split(/\r?\n/).map(line=>line.split(',').map(v=>v.trim()));return b.selectedTeams.map(code=>{const row=catalog.find(r=>r[1]===code)||[code,code,code];return{id:key(code),name:row[0]||code,aliases:[code,row[2]||code]};});}
async function catalog(){return (await get(ref(getDatabase(app()),'campNotifications/catalog'))).val()||{};}
function dialog(title,html){document.getElementById('cff-notify-dialog')?.remove();const d=document.createElement('dialog');d.id='cff-notify-dialog';d.className='cff-notify-dialog';d.innerHTML=`<h2>${esc(title)}</h2>${html}<p role="status" data-status></p><button type="button" class="cff-camp-btn" data-close>Fechar</button>`;d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());document.body.append(d);d.showModal();return d;}
async function configure(){
 try{const b=snapshot(),info=identity(b),list=await catalog(),teams=roster(b);const prior=info.id?list[info.id]:Object.values(list).find(t=>t.name===info.name);
 const priorId=info.id||Object.keys(list).find(id=>list[id]===prior)||'camp-'+crypto.randomUUID();
 const d=dialog('Avisos deste torneio',`<form><p><strong>${esc(info.name)}</strong></p><label><input name="enabled" type="checkbox" ${prior?.enabled?'checked':''}> Permitir avisos para este torneio</label><p>Somente os torneios marcados aparecem para as pessoas na conta. Os resultados lançados aqui são parciais.</p>${info.stage?'<p>A confirmação T1 + P1 da etapa FFWS vinculada transforma os avisos em oficiais.</p>':'<p>Este torneio fica como parcial. A confirmação automática está disponível nas etapas vinculadas à FFWS BR.</p>'}<button class="cff-camp-btn is-primary">Salvar configuração</button></form>`);
 d.querySelector('form').onsubmit=async e=>{e.preventDefault();const submit=e.target.querySelector('button');submit.disabled=true;try{await request('configure',{tournamentId:priorId,name:info.name,enabled:e.target.elements.enabled.checked,teams,officialStage:info.stage},app());d.querySelector('[data-status]').textContent='Configuração salva. As pessoas já podem escolher os avisos pela conta.';}catch(e){d.querySelector('[data-status]').textContent=e.message;}finally{submit.disabled=false;}};
 }catch(e){window.CFF_CAMP?.toast?.(e.message,'err');}
}
async function publish(){
 try{const b=snapshot(),info=identity(b),list=await catalog(),id=info.id||Object.keys(list).find(id=>list[id].name===info.name),t=list[id];if(!t?.enabled)throw Error('Abra Avisos do torneio e marque Permitir avisos primeiro.');
 const teams=roster(b).filter(r=>t.teams?.[r.id]),day=Number(b.tournamentModeV1?.draftDayNumber)||1,drop=Number(document.getElementById('drop-num')?.value)||1;
 const d=dialog('Confirmar eliminação e avisar',`<form><p><strong>${esc(info.name)}</strong> · Pontuação parcial</p><div class="fields"><label>Dia<input name="day" type="number" min="1" max="365" value="${day}" required></label><label>Queda<input name="drop" type="number" min="1" max="999" value="${drop}" required></label></div><label>Time<select name="team">${teams.map(r=>`<option value="${esc(r.id)}">${esc(r.name)}</option>`).join('')}</select></label><div class="preview" data-preview></div><p>Confira o resultado antes de enviar. Um novo clique para o mesmo time e queda não envia outro aviso. Correções do T1 + P1 aparecem como oficiais.</p><button class="cff-camp-btn is-primary">Confirmar eliminação e avisar</button></form>`);
 const f=d.querySelector('form'),status=d.querySelector('[data-status]');let row=null;
 function preview(){try{const latest=snapshot(),team=teams.find(r=>r.id===f.elements.team.value),code=latest.selectedTeams.find(c=>key(c)===team?.id),result=latest.drops?.[Number(f.elements.drop.value)-1];
 row={teamId:team.id,team:team.name,position:result?.placements?.[code],kills:result?.kills?.[code],points:result?.points?.[code]};
 const sameDay=Number(f.elements.day.value)===(Number(latest.tournamentModeV1?.draftDayNumber)||1);
 const valid=sameDay&&['position','kills','points'].every(k=>row[k]!==null&&row[k]!==''&&row[k]!==undefined&&Number.isFinite(Number(row[k])))&&!result?.unknownKills?.[code]&&!result?.estimatedKills?.[code];
 d.querySelector('[data-preview]').textContent=valid?`${team.name} · ${row.position}º · ${row.kills} abates · ${row.points} pontos`:'Preencha posição, abates e pontos reais na queda do dia aberto no painel.';f.querySelector('button').disabled=!valid;
 }catch{f.querySelector('button').disabled=true;}}
 f.addEventListener('change',preview);preview();f.onsubmit=async e=>{e.preventDefault();preview();const button=f.querySelector('button');if(button.disabled)return;button.disabled=true;try{const r=await request('publish',{tournamentId:id,day:Number(f.elements.day.value),drop:Number(f.elements.drop.value),result:row},app());status.textContent=r.duplicate?'Este aviso já foi enviado; nenhum duplicado foi criado.':'Aviso parcial confirmado. Será enviado para quem escolheu este torneio ou time.';}catch(e){status.textContent=e.message;}finally{button.disabled=false;}};
 }catch(e){window.CFF_CAMP?.toast?.(e.message,'err');}
}
function boot(){if(window.__CFF_CAMP_READY__!==true||!document.querySelector('.cff-camp-command'))return false;stylesheet();const row=document.createElement('div');row.className='cff-notify-admin';row.innerHTML='<button type="button" class="cff-camp-btn" data-config>🔔 Avisos do torneio</button><button type="button" class="cff-camp-btn" data-publish>Confirmar eliminação e avisar</button><a class="cff-camp-btn" href="/conta.html?tab=notifications" target="_blank" rel="noopener">Testar na minha conta ↗</a>';row.querySelector('[data-config]').onclick=configure;row.querySelector('[data-publish]').onclick=publish;document.querySelector('.cff-camp-command').append(row);return true;}
if(!boot()){let attempts=0;const timer=setInterval(()=>{if(boot()||++attempts>120)clearInterval(timer);},500);}
